### ISSUE TITLE
missing dependency or unstated assumption?

### ISSUE THREAD

**Issue by remster** [TheSavior/rewire-global#21]
var mod = require('module'); //<- there is no module named 'module'
and thus
var initialStart = mod.wrapper[0]; //<- throws

**Comment by elicwhite** [comment]
Hmm. `module` should be provided by node. It looks like this test suite is failing due to lint exceptions, let me see if I can get it passing again.

**Comment by elicwhite** [comment]
Build is passing. 

This module only works when run in node. Are you using browserify or webpack? If so, you may need a different library.
